repos:
-   repo: https://github.com/ambv/black
    rev: 21.5b0
    hooks:
    - id: black
      language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    - id: flake8
      args: ['--config=setup.cfg']
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
    -   id: reorder-python-imports
